apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: aksel-dashboard
  namespace: designsystem
  labels:
    team: designsystem
  annotations:
    nais.io/read-only-file-system: "false"
spec:
  image: {{ image }}
  port: 3000
  ingresses:
    - "https://aksel-dashboard.dev.nav.no"
  liveness:
    path: /api/isAlive
  readiness:
    path: /api/isAlive
  replicas:
    min: 1
    max: 1
  gcp:
    buckets:
      - name: aksel-dashboard
